# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/universal-windows-platform"
site_name: UWP

destination: _site
# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,
    introduction-wu.md,
    installation-and-deployment/wu-createapp.md,
    data-storage,
    controls/raddatagrid/features/data-storage-provider,
    telerik-examples/samples-demos.md,
    controls/radimageeditor,	
    controls/radhexview,
]
navigation:
## List your directory names and order here, like this:
    installation-and-deployment:
        title: "Installation and Deployment"
        position: 2   
    common:
        title: "Common Information"
        position: 3
    common/localization:
        title: "Localization"
        position: 4
    common/troubleshooting:
        title: "Troubleshooting"
        position: 5
    controls:
        title: "Controls"
        position: 4
    controls/radautocompletebox:
        title: "AutoCompleteBox"
        position: 1
    controls/radautocompletebox/features:
        title: "Features"
        position: 4
    controls/radautocompletebox/styling:
        title: "Styling"
        position: 4
    controls/radbulletgraph:
        title: "Bulletgraph"
        position: 1
    controls/radbulletgraph/customizing-radbulletgraph:
        title: "Customizing"
        position: 4
    controls/radbulletgraph/how-to:
        title: "How to"
        position: 
    controls/radbusyindicator:
        title: "Busy Indicator"
        position: 1
    controls/radcalendar:
        title: "Calendar"
        position: 1
    controls/radcalendar/commands:
        title: "Commands"
        position: 4
    controls/radcalendar/how-to:
        title: "How to"
        position: 
    controls/radcalendar/navigation-support:
        title: "Navigation Support"
        position: 4
    controls/radcalendar/styling:
        title: "Styling"
        position: 4
    controls/radimageeditor:
        title: "ImageEditor"
        position: 1
    controls/radchart:
        title: "Chart"
        position: 1
    controls/radchart/annotations:
        title: "Annotations"
        position: 4
    controls/radchart/axes:
        title: "Axes"
        position: 4
    controls/radchart/behaviors:
        title: "Behaviors"
        position: 4
    controls/radchart/cartesianchart:
        title: "CartesianChart"
        position: 4
    controls/radchart/cartesianchart/axes:
        title: "Axes"
        position: 4
    controls/radchart/cartesianchart/series:
        title: "Series"
        position: 4
    controls/radchart/how-to:
        title: "How to"
        position: 
    controls/radchart/labels:
        title: "Labels"
        position: 4
    controls/radchart/legend-control:
        title: "Legend Control"
        position: 4
    controls/radchart/piechart:
        title: "PieChart"
        position: 4
    controls/radchart/polarchart:
        title: "PolarChart"
        position: 4
    controls/radchart/polarchart/axes:
        title: "Axes"
        position: 4
    controls/radchart/polarchart/series:
        title: "Series"
        position: 4
    controls/radchart/series:
        title: "Series"
        position: 4
    controls/radchart/cartesianchart/series/categorical-series:
        title: "Categorical Series"
        position: 1
    controls/radchart/cartesianchart/series/scatter-series:
        title: "Scatter Series"
        position: 2
    controls/radchart/cartesianchart/series/ohlc-series:
        title: "OHLC Series"
        position: 3
    controls/radchart/cartesianchart/series/dynamic-series:
        title: "Dynamic Series"
        position: 4
    controls/radchart/polarchart/series/polar-series:
        title: "Polar Series"
        position: 1
    controls/radchart/polarchart/series/radar-series:
        title: "Radar Series"
        position: 2
    controls/radchart/styling:
        title: "Styling"
        position: 4
    controls/raddataboundlistbox:
        title: "DataboundListbox"
        position: 1
    controls/raddataboundlistbox/features:
        title: "Features"
        position: 4
    controls/raddataboundlistbox/item-animations:
        title: "Item Animations"
        position: 5
    controls/radexpander:
        title: "ExpanderControl"
        position: 1
    controls/raddataform:
        title: "DataForm"
        position: 1
    controls/raddataform/features:
        title: "Features"
        position: 2
    controls/raddataform/styling:
        title: "Styling"
        position: 3
    controls/raddatagrid:
        title: "DataGrid"
        position: 1
    controls/raddatagrid/features/aggregates:
        title: "Aggregates"
        position: 100
    controls/raddatagrid/columns:
        title: "Columns"
        position: 100
    controls/raddatagrid/columns/how-to:
        title: "How to"
        position: 1000
    controls/raddatagrid/features:
        title: "Features"
        position: 100
    controls/raddatagrid/features/commands:
        title: "Commands"
        position: 100
    controls/raddatagrid/features/commands/editing-commands:
        title: "Editing Commands"
        position:    
    controls/raddatagrid/features/editing:
        title: "Editing"
        position: 100
    controls/raddatagrid/features/filtering:
        title: "Filtering"
        position: 100
    controls/raddatagrid/features/filtering/how-to:
        title: "How To"
        position: 1000
    controls/raddatagrid/features/grouping:
        title: "Grouping"
        position: 100
    controls/raddatagrid/how-to:
        title: "How to"
        position: 1000
    controls/raddatagrid/features/sorting:
        title: "Sorting"
        position: 100
    controls/raddatagrid/styling:
        title: "Styling"
        position: 100
    controls/raddatepicker-and-radtimepicker:
        title: "DatePicker and TimePicker"
        position: 1
    controls/raddatepicker-and-radtimepicker/features:
        title: "Features"
        position: 4
    controls/raddatepicker-and-radtimepicker/properties-and-configuration:
        title: "Properties and Configuration"
        position: 4
    controls/raddatepicker-and-radtimepicker/styling:
        title: "Styling"
        position: 4
    controls/radgauge:
        title: "Gauge"
        position: 1
    controls/radgauge/gauges:
        title: "Gauges"
        position: 4
    controls/radgauge/how-to:
        title: "How to"
        position: 
    controls/radgauge/indicators:
        title: "Indicators"
        position: 4
    controls/radhexview:
        title: "HexView"
        position: 1
    controls/radhubtile:
        title: "Hubtile"
        position: 1
    controls/radhubtile/hubtiles:
        title: "Hubtiles"
        position: 4
    controls/radlistview:
        title: "ListView"
        position: 1
    controls/radlistview/features:
        title: "Features"
    controls/radloopinglist:
        title: "LoopingList"
        position: 1
    controls/radmap:
        title: "Map"
        position: 1
    controls/radmap/behaviors:
        title: "Behaviors"
        position: 4
    controls/radmap/layers:
        title: "Layers"
        position: 4
    controls/radmap/styling:
        title: "Styling"
        position: 4
    controls/radnumericbox:
        title: "NumericBox"
        position: 1
    controls/radnumericbox/styling:
        title: "Styling"
        position: 4
    controls/radpagination:
        title: "Pagination"
        position: 15
    controls/radpagination/properties-and-configuration:
        title: "Properties and Configuration"
        position: 4
    controls/radradialmenu:
        title: "Radial Menu"
        position: 1
    controls/radradialmenu/commands:
        title: "Commands"
        position: 4
    controls/radradialmenu/how-to:
        title: "How to"
        position: 
    controls/radradialmenu/styling:
        title: "Styling"
        position: 4
    controls/radrangeslider:
        title: "Range Slider"
        position: 1
    controls/radrangeslider/how-to:
        title: "How to"
        position: 
    controls/radrating:
        title: "Rating"
        position: 1 
    controls/radrating/features:
        title: "Features"
        position: 4            
    controls/radsidedrawer:
        title: "SideDrawer"
        position: 1
    controls/radshadow:
        title: "Shadow"
        position: 1
    telerik-examples:
        title: "Telerik Examples"
        position: 6
    cloud-integration:
        title: "Cloud Integration"
        position: 7
## Cloud Integration Sub-Folders
    cloud-integration/azure:
        title: "Azure"
        position: 1
    cloud-integration/azure/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 3				
    cloud-integration/azure/cognitive-services:
        title: "Cognitive Services"
        position: 5
    cloud-integration/amazon-web-services:
        title: "Amazon Web Services"
        position: 2
    cloud-integration/amazon-web-services/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 5
    cloud-integration/google-cloud:
        title: "Google Cloud"
        position: 3
    cloud-integration/google-cloud/cognitive-services:
        title: "Cognitive Services"
        position: 4
    cloud-integration/google-cloud/connect-to-data-in-the-cloud:
        title: "Connect to Data in the Cloud"
        position: 5
## Cloud Integration Sub-Folders		

## The application virtual path
baseurl: /devtools/universal-windows-platform

## The product name
productName: "Telerik UI for Universal Windows Platform"
product: "Telerik UI for Universal Windows Platform"
platform: uwp

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
-
    scope:
        path: "controls/radautocompletebox"
    values:
        title_prefix: "UWP AutoCompleteBox Documentation"
-
    scope:
        path: "controls/radbulletgraph"
    values:
        title_prefix: "UWP BulletGraph Documentation"   
-
    scope:
        path: "controls/radbusyindicator"
    values:
        title_prefix: "UWP BusyIndicator Documentation"   
-
    scope:
        path: "controls/radcalendar"
    values:
        title_prefix: "UWP Calendar Documentation"  
-
    scope:
        path: "controls/radchart"
    values:
        title_prefix: "UWP Chart Documentation"   
-
    scope:
        path: "controls/raddataboundlistbox"
    values:
        title_prefix: "UWP DataboundListbox Documentation"   
-
    scope:
        path: "controls/raddataform"
    values:
        title_prefix: "UWP DataForm Documentation"   
-
    scope:
        path: "controls/raddatagrid"
    values:
        title_prefix: "UWP DataGrid Documentation"   
-
    scope:
        path: "controls/raddatepicker-and-radtimepicker"
    values:
        title_prefix: "UWP DatePicker and TimePicker Documentation"  
-
    scope:
        path: "controls/radexpander"
    values:
        title_prefix: "UWP ExpanderControl Documentation"   
-
    scope:
        path: "controls/radgauge"
    values:
        title_prefix: "UWP Gauge Documentation"   
-
    scope:
        path: "controls/radhubtile"
    values:
        title_prefix: "UWP HubTile Documentation"   
-
    scope:
        path: "controls/radlistview"
    values:
        title_prefix: "UWP ListView Documentation"   
-
    scope:
        path: "controls/radloopinglist"
    values:
        title_prefix: "UWP LoopingList Documentation"
-
    scope:
        path: "controls/radmap"
    values:
        title_prefix: "UWP Map Documentation"         
-
    scope:
        path: "controls/radnumericbox"
    values:
        title_prefix: "UWP NumericBox Documentation"         
-
    scope:
        path: "controls/radradialmenu"
    values:
        title_prefix: "UWP RadialMenu Documentation"         
-
    scope:
        path: "controls/radrangeslider"
    values:
        title_prefix: "UWP RangeSlider Documentation"         
-
    scope:
        path: "controls/radrating"
    values:
        title_prefix: "UWP Rating Documentation"         
-
    scope:
        path: "controls/radsidedrawer"
    values:
        title_prefix: "UWP SideDrawer Documentation"         
-
    scope:
        path: "controls/radshadow"
    values:
        title_prefix: "UWP Shadow Documentation"         
        
    scope:
        path: "controls/radpagination"
    values:
        title_prefix: "UWP Pagination Documentation"                 

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Define any custom fields that you use in the site here
framework_name: Universal Windows Platform

# Feedback Form Google Sheet ID
ff-sheet-id: 14KlSrNfsdqMSwoJu2VX2mlAHvXTlkBBRilLZnmk42pU

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:lprcix5e19g'
gcs_api_key: 'AIzaSyDr_KcLnniwVyNmh0I339kr_aE2s6wmoxE'
has_api_reference: false

edit_repo_url: https://github.com/telerik/uwp-docs/edit/master
download: https://www.telerik.com/download-trial-file/v2-b/ui-for-universal-windows-platform
nav:
  "Demos": https://www.microsoft.com/en-us/p/telerik-ui-for-uwp-examples/9n3fgcz50qnl?activetab=pivot:overviewtab
  "Whats New": https://www.telerik.com/support/whats-new/uwp
  "Release History": https://www.telerik.com/support/whats-new/uwp/release-history
  "About": https://www.telerik.com/universal-windows-platform-ui
  "Pricing": https://www.telerik.com/purchase/universal-windows-platform

footer:
-
  title: "Getting Started"
  links:
    "Demos": https://www.microsoft.com/en-us/p/telerik-ui-for-uwp-examples/9n3fgcz50qnl?activetab=pivot:overviewtab
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/ui-for-universal-windows-platform
    "Blogs": https://www.telerik.com/blogs/mobile
    "Feedback Portal": https://feedback.telerik.com/Project/167
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM

